apiVersion: 1

contactPoints:
  - orgId: 1
    name: dz8-demo-webhook
    receivers:
      - uid: dz8-demo-webhook-receiver
        type: webhook
        settings:
          url: http://ml_service:8000/alert-webhook
          httpMethod: POST
        disableResolveMessage: false
