apiVersion: 1

policies:
  - orgId: 1
    receiver: dz8-demo-webhook
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: dz8-demo-webhook
        object_matchers:
          - - severity
            - =
            - warning
